server:
  #端口号
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loss_found?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: xxxxxxxx
    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc:
    template:
      query-timeout: 3        #查询超时时间


#配置mybatis规则
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml   #全局配置文件
  mapper-locations: classpath:mybatis/mapper/*.xml        #sql映射文件

#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.ynu.lossfound.mapper : debug